<a href="https://colab.research.google.com/github/tanusha3004/NumPy-Array-Utilities/blob/main/Numpy_Array_Creation_and_basic_functions_pynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [3]:
#initializing 1D array and 2D array
a=np.array([1.1,2.1,3.2,4.2,5.3,6.3])
a1 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])


In [4]:
# retrieving info about array using array attributes
print(a.shape,a.ndim,a.size,a.dtype)
print(a1.shape,a1.ndim,a1.size,a1.dtype)

# rank in numpy array is the no. of dimensions
print(np.linalg.matrix_rank(a))
print(np.linalg.matrix_rank(a1))

(6,) 1 6 float64
(3, 4) 2 12 int64
1
2


In [5]:
# accessing elements of a Numpy array
print(a[0])
print(a[3:])
print("\n")
print(a1[0])
print(a1[2][0])

# modifying elements of a Numpy array
# a[5]=6.36
# print(a)

1.1
[4.2 5.3 6.3]


[1 2 3 4]
9


Creation of numpy arrays using **np.array()**, **np.zeroes(), np.ones(),np.arange(),p.linspace()** and specify the datatypes explicitly if required using **dtype**

In [6]:
arr1=np.array([1,2,3])
zeroarr=np.zeros(2)
onesarr=np.ones(3)
rangearr=np.arange(11,44,11)
linearspc=np.linspace(0,15,num=3)

In [14]:
emptyarr=np.empty(4)
print(emptyarr)

[4.79983259e-310 0.00000000e+000 0.00000000e+000 0.00000000e+000]


In [7]:

import time

# Measure the execution time for np.ones()
start_time = time.time()
arr_ones = np.ones(100)
end_time = time.time()
execution_time_ones = end_time - start_time
print("Execution time for np.ones():", execution_time_ones, "seconds")

# Measure the execution time for np.empty()
start_time = time.time()
arr_empty = np.empty(3)
end_time = time.time()
execution_time_empty = end_time - start_time
print("Execution time for np.empty():", execution_time_empty, "seconds")


# Compare execution times
if execution_time_ones < execution_time_empty:
    print("np.ones() is faster")
elif execution_time_ones > execution_time_empty:
    print("np.empty() is faster")
else:
    print("Execution times are approximately equal")

Execution time for np.ones(): 0.0001685619354248047 seconds
Execution time for np.empty(): 0.00013494491577148438 seconds
np.empty() is faster


In [8]:
# 1D array vs 2D array
array1 = np.array([5, 6])
array2 = np.array([[5, 6]])# think of it as a single row matrix[[a,b]]

print("Array 1 shape:", array1.shape)  # Output: (2,)-> 2 elements
print("Array 2 shape:", array2.shape)  # Output: (1, 2)-> 2 dimensions, 1 row, 2 col

Array 1 shape: (2,)
Array 2 shape: (1, 2)


np.concatenate((a,b)) and np.sort(a)

In [9]:
#np.concatenate((a1, a2, ...), axis=0, out=None, dtype=None, casting="same_kind")
x = np.array([[1, 2], [3, 4]])
print(x.shape)
y = np.array([[5, 6]])
print(y.shape)
print(np.concatenate((x,y),axis=0))

#np.sort()
arr=np.array([2,8,4,6,5,3,1,7])
print(arr.sort)


(2, 2)
(1, 2)
[[1 2]
 [3 4]
 [5 6]]
<built-in method sort of numpy.ndarray object at 0x783924526490>
